import type { ParsedDocument } from "@/types";

export const DEMO_SCHOLARSHIP: ParsedDocument = {
  id: "demo-scholarship-1",
  title: "Post-Matric Scholarship for SC/ST Students - 2025-26",
  issuingAuthority: "Ministry of Social Justice & Empowerment, Government of India",
  category: "scholarship",
  purpose: "Financial assistance for SC/ST students pursuing post-matriculation education",
  deadline: "2026-03-31",
  importantDates: [
    { label: "Application Start", date: "2025-07-01" },
    { label: "Application Deadline", date: "2026-03-31" },
    { label: "Verification Period", date: "2026-04-15" },
    { label: "Disbursement", date: "2026-06-01" },
  ],
  eligibilityCriteria: [
    "Must belong to SC/ST category with valid caste certificate",
    "Annual family income should be below Rs.2,50,000",
    "Must be enrolled in post-matriculation course at recognized institution",
    "Minimum 50% marks in previous qualifying examination",
    "Must have a valid Aadhaar number linked to bank account",
  ],
  restrictions: [
    "Students studying in private unaided institutions not eligible for tuition fee component",
    "Only 2 children per family eligible (elder sibling restriction)",
    "Students who have already received scholarship for same course year not eligible",
  ],
  requiredFields: [
    { id: "f1", name: "Full Name", description: "Name as per Aadhaar card", type: "text", required: true },
    { id: "f2", name: "Date of Birth", description: "Date of birth", type: "date", required: true },
    { id: "f3", name: "Gender", description: "Gender", type: "select", required: true, options: ["Male", "Female", "Other"] },
    { id: "f4", name: "Category", description: "Social category", type: "select", required: true, options: ["SC", "ST"] },
    { id: "f5", name: "Aadhaar Number", description: "12-digit Aadhaar number", type: "text", required: true },
    { id: "f6", name: "Institution Name", description: "Name of college/university", type: "text", required: true },
    { id: "f7", name: "Course Name", description: "Name of course enrolled", type: "text", required: true },
    { id: "f8", name: "Year of Study", description: "Current year of study", type: "select", required: true, options: ["1st Year", "2nd Year", "3rd Year", "4th Year"] },
    { id: "f9", name: "Previous Percentage", description: "Percentage in last qualifying exam", type: "number", required: true },
    { id: "f10", name: "Annual Family Income", description: "Total annual family income in Rs.", type: "number", required: true },
    { id: "f11", name: "Bank Account Number", description: "Account number for scholarship disbursement", type: "text", required: true },
    { id: "f12", name: "IFSC Code", description: "Bank IFSC code", type: "text", required: true },
  ],
  requiredAttachments: [
    { id: "a1", name: "Caste Certificate", description: "SC/ST caste certificate from competent authority", format: "PDF", mandatory: true, urgency: "high", sectionReference: "Section 4.2" },
    { id: "a2", name: "Income Certificate", description: "Family income certificate from Tehsildar/SDM", format: "PDF", mandatory: true, urgency: "high", sectionReference: "Section 4.3" },
    { id: "a3", name: "Aadhaar Card", description: "Scanned copy of Aadhaar card", format: "PDF/JPG", mandatory: true, urgency: "high", sectionReference: "Section 4.1" },
    { id: "a4", name: "Previous Year Marksheet", description: "Mark sheet of last qualifying examination", format: "PDF", mandatory: true, urgency: "medium", sectionReference: "Section 4.4" },
    { id: "a5", name: "Bank Passbook", description: "First page of bank passbook showing account details", format: "PDF/JPG", mandatory: true, urgency: "medium", sectionReference: "Section 4.5" },
    { id: "a6", name: "Admission Letter", description: "Current year admission/bonafide certificate", format: "PDF", mandatory: false, urgency: "low", sectionReference: "Section 4.6" },
  ],
  fees: null,
  signatureRequirements: ["Signature of applicant", "Signature of institution head", "Seal of institution"],
  sections: [
    { id: "s1", title: "Objective", content: "The Post-Matric Scholarship scheme aims to provide financial assistance to SC/ST students studying at post-matriculation level to enable them to complete their education.", pageNumber: 1 },
    { id: "s2", title: "Eligibility", content: "Students belonging to Scheduled Castes and Scheduled Tribes who are pursuing post-matriculation studies in recognized institutions. Annual family income should not exceed Rs.2,50,000. Student must have passed the matriculation examination or higher secondary examination.", pageNumber: 1 },
    { id: "s3", title: "Scholarship Amount", content: "Maintenance allowance: Rs.380/month for hostellers, Rs.120/month for day scholars. Tuition fees as per actuals up to ceiling. Non-refundable charges as per actuals.", pageNumber: 2 },
    { id: "s4", title: "Required Documents", content: "1. Caste Certificate from competent authority\n2. Income Certificate from Tehsildar\n3. Aadhaar card\n4. Previous year marksheet\n5. Bank passbook first page\n6. Admission letter / Bonafide certificate", pageNumber: 2 },
    { id: "s5", title: "Application Process", content: "Apply online through National Scholarship Portal (scholarship.gov.in). Upload required documents. Institute verification within 30 days. District verification within 15 days of institute verification.", pageNumber: 3 },
  ],
  rawText: "Post-Matric Scholarship for SC/ST Students 2025-26. Ministry of Social Justice. Income below Rs.2.5 lakh. 50% marks required. Deadline March 31, 2026. Apply at scholarship.gov.in.",
  summary: "This is a government scholarship for SC/ST students pursuing post-matriculation education. It covers tuition fees and provides maintenance allowance. Family income must be below Rs.2.5 lakh annually. Students need 50% in their previous exam. Applications are through the National Scholarship Portal.",
  risks: [
    { id: "r1", title: "Deadline approaching", description: "Application deadline is March 31, 2026. Submit at least 2 weeks before for institute verification.", severity: "high" },
    { id: "r2", title: "Aadhaar linking required", description: "Bank account must be linked with Aadhaar for direct benefit transfer.", severity: "high" },
    { id: "r3", title: "2-child restriction", description: "Only 2 children per family can receive this scholarship simultaneously.", severity: "medium" },
    { id: "r4", title: "Institute verification delay", description: "Institute must verify within 30 days. Follow up with institution proactively.", severity: "medium" },
  ],
  documentType: "scholarship",
};

export const DEMO_REIMBURSEMENT: ParsedDocument = {
  id: "demo-reimbursement-1",
  title: "Employee Medical Reimbursement Claim Form - 2025",
  issuingAuthority: "HR Department, ABC Technologies Pvt. Ltd.",
  category: "reimbursement",
  purpose: "Claim reimbursement for medical expenses incurred by employee or dependents",
  deadline: null,
  importantDates: [
    { label: "Claim Submission Window", date: "Within 60 days of expense" },
    { label: "Annual Limit Reset", date: "January 1 each year" },
    { label: "Processing Time", date: "7-10 working days" },
  ],
  eligibilityCriteria: [
    "Must be a confirmed employee with minimum 6 months tenure",
    "Expenses must be for self or declared dependent",
    "Treatment must be from registered medical practitioner or hospital",
    "Original receipts and prescriptions required",
    "Annual ceiling of Rs.50,000 for self, Rs.25,000 per dependent",
  ],
  restrictions: [
    "Cosmetic surgery and elective procedures not covered",
    "Over-the-counter medicines not reimbursable without prescription",
    "Claims older than 60 days from date of expense not accepted",
    "Pre-existing conditions: first Rs.5,000 deductible applies",
  ],
  requiredFields: [
    { id: "rf1", name: "Employee ID", description: "Your employee identification number", type: "text", required: true },
    { id: "rf2", name: "Employee Name", description: "Full name as per HR records", type: "text", required: true },
    { id: "rf3", name: "Department", description: "Department name", type: "text", required: true },
    { id: "rf4", name: "Patient Name", description: "Name of person who received treatment", type: "text", required: true },
    { id: "rf5", name: "Relationship", description: "Relationship to employee", type: "select", required: true, options: ["Self", "Spouse", "Child", "Parent"] },
    { id: "rf6", name: "Date of Treatment", description: "Date when treatment was received", type: "date", required: true },
    { id: "rf7", name: "Hospital/Clinic Name", description: "Name of medical facility", type: "text", required: true },
    { id: "rf8", name: "Diagnosis", description: "Medical diagnosis or complaint", type: "text", required: true },
    { id: "rf9", name: "Total Amount", description: "Total amount claimed in Rs.", type: "number", required: true },
    { id: "rf10", name: "Payment Mode", description: "How payment was made", type: "select", required: true, options: ["Cash", "Card", "UPI", "Online Transfer"] },
  ],
  requiredAttachments: [
    { id: "ra1", name: "Medical Bills", description: "Original itemized hospital/clinic bills", format: "PDF/Original", mandatory: true, urgency: "high", sectionReference: "Clause 3.1" },
    { id: "ra2", name: "Prescription", description: "Doctor's prescription for medicines", format: "PDF/JPG", mandatory: true, urgency: "high", sectionReference: "Clause 3.2" },
    { id: "ra3", name: "Pharmacy Bills", description: "Bills for medicines purchased", format: "PDF/Original", mandatory: false, urgency: "medium", sectionReference: "Clause 3.3" },
    { id: "ra4", name: "Discharge Summary", description: "If hospitalization, discharge summary required", format: "PDF", mandatory: false, urgency: "medium", sectionReference: "Clause 3.4" },
    { id: "ra5", name: "Lab Reports", description: "Diagnostic test reports if applicable", format: "PDF/JPG", mandatory: false, urgency: "low", sectionReference: "Clause 3.5" },
  ],
  fees: null,
  signatureRequirements: ["Employee signature on claim form", "Reporting manager approval"],
  sections: [
    { id: "sr1", title: "Policy Coverage", content: "Medical reimbursement covers consultation fees, diagnostic tests, medicines, and hospitalization expenses. Annual ceiling: Rs.50,000 for self, Rs.25,000 per dependent.", pageNumber: 1 },
    { id: "sr2", title: "Claim Procedure", content: "1. Fill this form completely\n2. Attach original bills and prescriptions\n3. Get reporting manager approval\n4. Submit to HR within 60 days of expense\n5. Reimbursement processed in 7-10 working days", pageNumber: 1 },
    { id: "sr3", title: "Exclusions", content: "Not covered: Cosmetic surgery, elective procedures, over-the-counter medicines without prescription, dental implants, eyewear beyond Rs.3,000.", pageNumber: 2 },
  ],
  rawText: "Employee Medical Reimbursement Claim Form 2025. ABC Technologies. Coverage Rs.50,000 self, Rs.25,000 dependent. Deadline 60 days. Processing 7-10 days. Required: Original bills, prescriptions, manager approval.",
  summary: "This is an internal medical reimbursement form for employees of ABC Technologies. It covers medical expenses up to Rs.50,000 annually for self and Rs.25,000 per dependent. Claims must be submitted within 60 days. Original bills and prescriptions are mandatory.",
  risks: [
    { id: "rr1", title: "60-day window", description: "Claims submitted after 60 days from date of expense will be rejected.", severity: "high" },
    { id: "rr2", title: "Original receipts mandatory", description: "Photocopies are not accepted. Ensure you have original bills.", severity: "high" },
    { id: "rr3", title: "Deductible for pre-existing", description: "First Rs.5,000 of pre-existing condition treatment is not reimbursable.", severity: "medium" },
  ],
  documentType: "reimbursement",
};

export const DEMO_ADMISSION: ParsedDocument = {
  id: "demo-admission-1",
  title: "B.Tech Computer Science Admission Application - 2026",
  issuingAuthority: "National Institute of Technology (NIT) Admissions Office",
  category: "admission",
  purpose: "Application for admission to B.Tech Computer Science program",
  deadline: "2026-06-15",
  importantDates: [
    { label: "Application Portal Opens", date: "2026-04-01" },
    { label: "Application Deadline", date: "2026-06-15" },
    { label: "JEE Main Score Submission", date: "2026-06-30" },
    { label: "Counselling Round 1", date: "2026-07-15" },
    { label: "Seat Allotment", date: "2026-07-20" },
    { label: "Reporting at Institute", date: "2026-08-01" },
  ],
  eligibilityCriteria: [
    "JEE Main 2026 qualified with valid score",
    "12th pass with Physics, Chemistry, and Mathematics",
    "Minimum 75% aggregate in 12th board (or top 20 percentile)",
    "Age: Candidate must have been born on or after October 1, 2001",
    "Indian nationality or OCI card holder",
  ],
  restrictions: [
    "Only JEE Main 2026 scores accepted, previous year scores not valid",
    "Seats are non-transferable",
    "Medical fitness certificate required at reporting",
    "Original documents must be presented during counselling",
  ],
  requiredFields: [
    { id: "af1", name: "Full Name", description: "Name as per 10th marksheet", type: "text", required: true },
    { id: "af2", name: "JEE Main Roll Number", description: "JEE Main 2026 roll number", type: "text", required: true },
    { id: "af3", name: "JEE Main Score", description: "NTA score out of 300", type: "number", required: true },
    { id: "af4", name: "JEE Main Rank", description: "All India rank in JEE Main", type: "number", required: true },
    { id: "af5", name: "Category", description: "JEE Main category", type: "select", required: true, options: ["GEN", "OBC-NCL", "SC", "ST", "EWS"] },
    { id: "af6", name: "12th Board Name", description: "Name of 12th standard board", type: "text", required: true },
    { id: "af7", name: "12th Percentage", description: "Aggregate percentage in 12th", type: "number", required: true },
    { id: "af8", name: "12th Year of Passing", description: "Year of passing 12th", type: "select", required: true, options: ["2024", "2025", "2026"] },
    { id: "af9", name: "Preferred Campus", description: "Preferred NIT campus", type: "select", required: true, options: ["NIT Trichy", "NIT Warangal", "NIT Surathkal", "NIT Calicut", "NIT Rourkela"] },
    { id: "af10", name: "Contact Email", description: "Active email for communication", type: "text", required: true },
    { id: "af11", name: "Contact Phone", description: "Active phone number", type: "text", required: true },
    { id: "af12", name: "Address", description: "Correspondence address", type: "text", required: true },
  ],
  requiredAttachments: [
    { id: "aa1", name: "10th Marksheet", description: "Class 10 marksheet from recognized board", format: "PDF", mandatory: true, urgency: "high", sectionReference: "Section 5.1" },
    { id: "aa2", name: "12th Marksheet", description: "Class 12 marksheet from recognized board", format: "PDF", mandatory: true, urgency: "high", sectionReference: "Section 5.2" },
    { id: "aa3", name: "JEE Main Score Card", description: "NTA score card for JEE Main 2026", format: "PDF", mandatory: true, urgency: "high", sectionReference: "Section 5.3" },
    { id: "aa4", name: "Aadhaar Card", description: "Scanned copy of Aadhaar card", format: "PDF/JPG", mandatory: true, urgency: "medium", sectionReference: "Section 5.4" },
    { id: "aa5", name: "Category Certificate", description: "SC/ST/OBC-NCL/EWS certificate if applicable", format: "PDF", mandatory: false, urgency: "medium", sectionReference: "Section 5.5" },
    { id: "aa6", name: "Passport Photo", description: "Recent passport size photograph", format: "JPG", mandatory: true, urgency: "medium", sectionReference: "Section 5.6" },
    { id: "aa7", name: "Transfer Certificate", description: "School/college transfer certificate", format: "PDF", mandatory: false, urgency: "low", sectionReference: "Section 5.7" },
    { id: "aa8", name: "Medical Fitness Certificate", description: "From registered medical practitioner", format: "PDF", mandatory: false, urgency: "low", sectionReference: "Section 5.8" },
  ],
  fees: "Application fee: Rs.1,000 (General/OBC), Rs.500 (SC/ST/PwD)",
  signatureRequirements: ["Candidate signature", "Parent/Guardian signature"],
  sections: [
    { id: "sa1", title: "Program Details", content: "B.Tech Computer Science and Engineering. Duration: 4 years (8 semesters). Total seats: 120. Fee structure: Rs.1,50,000 per year (tuition) + Rs.45,000 (hostel + mess). Scholarships available for economically weaker sections.", pageNumber: 1 },
    { id: "sa2", title: "Eligibility Requirements", content: "JEE Main 2026 qualified. 12th with PCM. Minimum 75% aggregate or top 20 percentile. Age limit: born on or after Oct 1, 2001.", pageNumber: 1 },
    { id: "sa3", title: "Selection Process", content: "Selection based on JEE Main All India Rank through JoSAA counselling. Choice filling determines seat allotment. Document verification at reporting.", pageNumber: 2 },
    { id: "sa4", title: "Fee Payment", content: "Application fee: Rs.1,000 (Gen/OBC), Rs.500 (SC/ST/PwD). Pay online through portal. Semester fee payable before each semester start.", pageNumber: 2 },
    { id: "sa5", title: "Required Documents for Reporting", content: "Original mark sheets, JEE score card, Aadhaar, category certificate, transfer certificate, migration certificate, medical fitness certificate, 6 passport photos.", pageNumber: 3 },
  ],
  rawText: "B.Tech Computer Science Admission Application 2026. NIT Admissions. JEE Main 2026 required. 12th with PCM, min 75%. Deadline June 15, 2026. Counselling July 15, 2026. Fee Rs.1,000. Seats: 120. Yearly fee Rs.1,50,000.",
  summary: "This is an admission application for B.Tech Computer Science at NIT. Requires JEE Main 2026 qualification, 75% in 12th, and application through JoSAA counselling. Total seats: 120. Annual fee: Rs.1,50,000. Counselling starts July 15, 2026.",
  risks: [
    { id: "ra_r1", title: "JEE Main 2026 score mandatory", description: "Without a valid JEE Main 2026 score, application will be rejected.", severity: "high" },
    { id: "ra_r2", title: "75% threshold is strict", description: "Students below 75% in 12th or not in top 20 percentile will not be eligible.", severity: "high" },
    { id: "ra_r3", title: "Seat competition", description: "With 120 seats and thousands of applicants, ensure your JEE rank is competitive.", severity: "medium" },
    { id: "ra_r4", title: "Original documents at counselling", description: "Failure to present originals at counselling results in seat cancellation.", severity: "high" },
  ],
  documentType: "admission",
};
